### PR TITLE
For more friendly to VSCode and cross build

### PR DESCRIPTION
**Pull request by kumajaya**
Visual Studio Code available on Linux, Windows, and Mac and more lightweight than Microsoft Visual Studio 2022. This patch will enable to build RapidScada 6 on OS where VS Code run. Add "C# for Visual Studio Code" and "Visual Studio .sln file explorer for Visual Studio Code" extension and VS Code ready to build RapidScada 6 from source.

### CODE REVIEW

**Comment by 2mik** [comment]
In the commit EnableWindowsTargeting was added to all WinForms project, right? How does it work for VS and VS Code?
In ScadaServerSvc.csproj a ItemGroup referenced Microsoft.NETFramework.ReferenceAssemblies was added? What purpose to add it?

**Comment by kumajaya** [comment]
1. EnableWindowsTargeting property to true solve NETSDK1100 error indicates that we're building a project that targets Windows on Linux or macOS. Reference: https://learn.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1100
2. Microsoft.NETFramework.ReferenceAssemblies benefit us to:
    - Build without requiring admin operations to install pre-requisites .NET Framework.
    - Build libraries on any operating system supported by the .NET Core SDK.
    - Build Mono-based projects.

    Reference: https://github.com/Microsoft/dotnet/tree/main/releases/reference-assemblies

Both actually not specific for VS Code but cross build dotnet development in general. Even on Windows, I avoid to download .NET Framework targeting packs since a complete .NET 6.0 SDK already installed.

**Comment by kumajaya** [comment]
I managed to run ScadaAdmin for Windows target on Linux with Wine help. I publish ScadaAdmin with `dotnet publish ScadaAdmin.sln -c Release -r win-x64 -p:PublishReadyToRun=true` command.

**Comment by 2mik** [comment]
I should check the approach before merging the files.

> I managed to run ScadaAdmin for Windows target on Linux with Wine help
That's cool! Could you create a new topic an the forum and share your experience with ScadaAdmin and Wine?

**Comment by kumajaya** [comment]
I believe this patch no harm to the current Visual Studio build system.

**Comment by kumajaya** [comment]
> That's cool! Could you create a new topic on the forum and share your experience with ScadaAdmin and Wine? Is it possible to use ScadaAdmin.exe built for Windows or we need some special steps?

Need a special ScadaAdmin build to avoid library dependency hell. Wine not always easy. I'll try to write it up.

**Comment by 2mik** [comment]
> Need a special ScadaAdmin build to avoid library dependency hell

What conflicts occur?

**Comment by kumajaya** [comment]
> Could you make a pull request that only adds the EnableWindowsTargeting property to necessary projects? Please put EnableWindowsTargeting on the next line after UseWindowsForms, because they have a close meaning. For example:
> 
> ```
>     <UseWindowsForms>true</UseWindowsForms>
>     <EnableWindowsTargeting>true</EnableWindowsTargeting>
> ```

Wait a minutes...

**Comment by kumajaya** [comment]
Looks like I have to close this pull request.

**Comment by kumajaya** [comment]
Closed for more clean patch.

**Comment by 2mik** [comment]
Note: hidden files .vscode, created by VS Code, should not be committed to GitHub.

**Comment by kumajaya** [comment]
> Note: hidden files .vscode, created by VS Code, should not be committed to GitHub.

I have no choice for VS Code automate jobs: https://code.visualstudio.com/docs/editor/tasks

**Comment by zcattacz** [comment]
There are another 3 additional files to patch.

        modified:   ScadaComm/OpenDrivers/DrvDbImport.View/DrvDbImport.View.csproj
        modified:   ScadaComm/OpenDrivers/DrvEnronModbus.View/DrvEnronModbus.View.csproj
        modified:   ScadaComm/OpenDrivers2/DrvSnmp.View/DrvSnmp.View.csproj

Maybe there should be a shell script for packing in Linux to cover all these corner stuff.

```
fix_windowstarget() {
    # patch new projects without #EnableWindowsTargeting flag
    for f in $(grep "<UseWindowsForms>true<\/UseWindowsForms>" -r . -l) ; do
        if ! grep -q -E "<EnableWindowsTargeting" $f ; then
            echo fix_windowstarget: $f
            sed -i -E "s#<UseWindowsForms>true<\/UseWindowsForms>#<UseWindowsForms>true<\/UseWindowsForms>\r\n    <EnableWindowsTargeting>true</EnableWindowsTargeting>#g" $f
        fi
    done
}
```

**Comment by 2mik** [comment]
Thank you for the notice. EnableWindowsTargeting has been added in the develop branch

**Pull request closed without merging**
