### PR TITLE
ScadaAdmin: Get rid start page glitch on Wine

### PR DESCRIPTION
**Pull request by kumajaya**

### CODE REVIEW

**Comment by 2mik** [comment]
Thank you for the pull request. To be able to merge it, the fix should be reproduced and tested by my side. Please provide additional info:
1. Instructions how to build and run Administrator using Wine.
2. Screenshots described the issue.

**Comment by 2mik** [comment]
Refresh should be executed in the start page itself. See https://github.com/RapidScada/scada-v6/commit/102f8963b6aff5346eba9e43486db98ce34e4862

**Comment by 2mik** [comment]
Thank you for your help to run ScadaAdmin on Wine!

**Comment by kumajaya** [comment]
> Thank you for your help to run ScadaAdmin on Wine!

You're welcome. Rapid SCADA very good solution.

**Pull request closed without merging**
