### PR TITLE
LangPack: Add initial Indonesian languange support

### PR DESCRIPTION
**Pull request by kumajaya**
Better with my previous pull request but not depend on it.

### CODE REVIEW

**Comment by 2mik** [comment]
Thanks!
May I ask you did you use up to date source language files for the translation?

**Comment by 2mik** [comment]
Let's keep `name="Indonesian"` in your translation. It can be a reminder for the future change of other files.

**Comment by 2mik** [comment]
Could you change
```
<ScadaWebDictionaries name="Indonesian">
  <General>
    <CultureName>id-ID</CultureName>
  </General>

```

to
`<ScadaWebDictionaries lang="Indonesian" culture="id-ID">`
?
It seems more consistent.

**Comment by kumajaya** [comment]
> Could you change
> 
> ```
> <ScadaWebDictionaries name="Indonesian">
>   <General>
>     <CultureName>id-ID</CultureName>
>   </General>
> ```
> 
> to `<ScadaWebDictionaries culture="id-ID" lang="Indonesian">` ? It seems more consistent.

OK. I'll also check how to make an adaption to Xml Content Translator.

**Comment by kumajaya** [comment]
> Thanks! May I ask you did you use up to date source language files for the translation?

Yes, of course. Thanks for the merge.

**Pull request merged**
